### ISSUE TITLE
Bad render

### ISSUE THREAD

**Issue by CondeCero** [bl4ckscor3/CeilingTorch#46]
When torch is placed in the cleiling it is showed as a pink/black block

**Comment by bl4ckscor3** [comment]
Thanks for reporting! I know the issue here, it's a stupid oversight on my part. For the next time when you report a bug, please include the Minecraft version and the mod version. 99% of the time knowing them is useful and necessary information. 

In any case, redownload v1.13.2 and it will be fixed.
