### ISSUE TITLE
[1.14.4] Loot Table warning when missing supported mod

### ISSUE THREAD

**Issue by Wynadorn** [bl4ckscor3/CeilingTorch#5]
Hey bl4ckscor3,

When not using _I Like Wood_ or _Bone Torch_ an error shows up.
````
22:00:50 [ERROR] [minecraft/LootTableManager] Couldn't parse loot table ceilingtorch:blocks/bonetorch_bonetorch
22:00:50 com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'bonetorch:bonetorch'
````
https://paste.ubuntu.com/p/yH7yvdw3FK/

minecraft_server.1.14.4.jar
forge-1.14.4-28.1.1.jar
ceilingtorch-1.14.4-v1.2.2.jar

**Comment by bl4ckscor3** [comment]
There's not really much I can do about this since Minecraft apparently tries to load loot tables even if their corresponding blocks are not present. I could circumvent this by not using loot tables, but that would defeat the purpose of using them (cannot be overridden by datapacks). I'm indifferent.

The error itself isn't really that major, it only logs that a loot table has failed to load. It doesn't impact gameplay.

**Comment by Wynadorn** [comment]
All right, thank you for having a look at it either way.
