### ISSUE TITLE
[1.18.1] Malum Mod Compat broken, crash.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#55]
Title^

Game crashes when loaded together with Malum mod.

**Crash-Report**: https://gist.github.com/Gbergz/6495f9cb255174b75524172734e64cf6

Minecraf: 1.18.1
Forge: 39.0.75
Ceiling Torch: 1.14 | https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/3606791
Malum: 1.2.2 | https://www.curseforge.com/minecraft/mc-mods/malum/files/3649085

**-** Gbergz

**Comment by Gbergz** [comment]
Update: 1.18.2 now, crashing again with newest Malum update:
https://gist.github.com/Gbergz/96f3f13124c52bca1c7989ab890aa711

**Comment by bl4ckscor3** [comment]
I took note of this now, but please create a new issue in the future. What you posted has nothing to do with the issue it got posted in. This issue has already been resolved and marked as fixed. This means nothing needs to be done anymore and even if something to the same effect is happening it's still caused by something different (because the original thing got fixed(!)), which means it does not make sense to post a new crash in an old issue.
