### ISSUE TITLE
Resource Pack Compat

### ISSUE THREAD

**Issue by QwertRvg** [bl4ckscor3/CeilingTorch#74]
Can you please add resource pack support? So the mod simply loads the torch and particle textures that the vanilla torch uses?
Otherwise the Ceiling Torch looks out of place when using a resource pack.
![image](https://github.com/bl4ckscor3/CeilingTorch/assets/89683173/f4e93231-f731-4c2c-aed6-d8f679b7ef14)

**Comment by bl4ckscor3** [comment]
It should already do that, since I don't touch models or textures. The only issue that could appear and which isn't fixable by the mod is if a resource pack changes the torch's block state file. In that case, the one from the ceiling torch doesn't match the vanilla one, and it has to be manually adapted.

Which Minecraft and Ceiling Torch versions are you using? Which resource pack is this?

**Comment by QwertRvg** [comment]
Hi, thanks for your response!
I am on Minecraft version 1.20.1, Forge 47.2.0 and Ceiling Torch 1.28.
And the Resource Pack I am using is [Torches Reimagined](https://www.curseforge.com/minecraft/texture-packs/torches-reimagined).

**Comment by bl4ckscor3** [comment]
Yup, as I expected the resource pack changes the blockstate files to redirect to its own model files. Frankly, I would consider this a bug in that resource pack, as it doesn't modify the vanilla torch's block model files instead. I attached a resource pack that fixes the ceiling torch visuals, but I'd suggest reporting this to the resource pack dev, as any block that uses the vanilla torch models will not take on the reimagined look.

[Torches Reimagined fix for Ceiling Torch.zip](https://github.com/bl4ckscor3/CeilingTorch/files/15152631/Torches.Reimagined.fix.for.Ceiling.Torch.zip)

**Comment by QwertRvg** [comment]
thanks so much!
